data_vars: [
    "shot_num",
    "date_dec",
    "doy",
    "lon_lm_a0",
    "lat_lm_a0",
    "elev_lm_a0",
    "elev_hr_a0",
    "elev_dem_srtm",
    "elev_dem_tdx",
    "elev_diff_dem",
    "sens_a0",
    "sens_a1",
    "sens_a2",
    "sens_a3",
    "sens_a4",
    "sens_a5",
    "sens_a6",
    "sens_a10",
    "energy_total",
    "ls_treecov",
    "ls_waterp",
    "leafoff_flag",
    "leafoff_doy",
    "leafon_doy",
    "pft",
    "region",
    "urb_prop",
    "num_modes_a0",
    "rh_0_a0",
    "rh_5_a0",
    "rh_10_a0",
    "rh_15_a0",
    "rh_20_a0",
    "rh_25_a0",
    "rh_30_a0",
    "rh_35_a0",
    "rh_40_a0",
    "rh_45_a0",
    "rh_50_a0",
    "rh_55_a0",
    "rh_60_a0",
    "rh_65_a0",
    "rh_70_a0",
    "rh_75_a0",
    "rh_80_a0",
    "rh_85_a0",
    "rh_90_a0",
    "rh_92_a0",
    "rh_95_a0",
    "rh_98_a0",
    "rh_99_a0",
    "rh_100_a0",
    "rhvdr_b",
    "rhvdr_m",
    "rhvdr_t",
    "l2b_algrun_flag",
    "l2b_qflag_a0",
    "pgap_theta_a0",
    "pgap_theta_err_a0",
    "fhd_pai_1m_a0",
    "cover_a0",
    "cover_l1",
    "cover_l2",
    "cover_l3",
    "cover_l4",
    "cover_l5",
    "cover_l6",
    "cover_l7",
    "cover_l8",
    "cover_l9",
    "cover_l10",
    "cover_l11",
    "cover_l12",
    "cover_l13",
    "cover_l14",
    "cover_l15",
    "cover_l16",
    "cover_l17",
    "cover_l18",
    "cover_l19",
    "cover_l20",
    "cover_l21",
    "pai_a0",
    "pai_l1",
    "pai_l2",
    "pai_l3",
    "pai_l4",
    "pai_l5",
    "pai_l6",
    "pai_l7",
    "pai_l8",
    "pai_l9",
    "pai_l10",
    "pai_l11",
    "pai_l12",
    "pai_l13",
    "pai_l14",
    "pai_l15",
    "pai_l16",
    "pai_l17",
    "pai_l18",
    "pai_l19",
    "pai_l20",
    "pai_l21",
    "pavd_0_5",
    "pavd_5_10",
    "pavd_10_15",
    "pavd_15_20",
    "pavd_20_25",
    "pavd_25_30",
    "pavd_30_35",
    "pavd_35_40",
    "pavd_40_45",
    "pavd_45_50",
    "pavd_50_55",
    "pavd_55_60",
    "pavd_60_65",
    "pavd_65_70",
    "pavd_70_75",
    "pavd_75_80",
    "pavd_80_85",
    "pavd_85_90",
    "pavd_90_95",
    "pavd_95_100",
    "pavd_0_5_frac",
    "pavd_bot_frac",
    "pavd_top_frac",
    "pavd_max_h",
    "even_pai_1m_a0",
    "fhd_pavd_5m_a0",
    "even_pavd_5m_a0",
    "l2_hqflag",
    "l2a_selalg_a0",
    "l4a_hqflag",
    "beam",
    "agbd_a0",
    "agbd_se_a0",
    "agbd_pi_low_a0",
    "agbd_pi_upper_a0",
    "treecover2000",
    "lossyear",
    "datamask",
    "enmap_date_dec",
    "enmap_doy",
    "delta_t_days"
]
