# @package _global_

defaults:
  - _self_
  - data: enmap_gedi # choose datamodule with `test_dataloader()` for evaluation
  - model: regression
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /path/to/checkpoint.ckpt
